[package]
name = "swayscratchpad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.16.2"
gtk-layer-shell = "^0.5.0"
shrinkwraprs = "^0.3.0"
cascade = "^1.0.1"
swayipc = "^3.0.1"
